### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by rowleyaj**

### CODE REVIEW

**Comment by vaijab** [comment]
Hey @rowleyaj, thanks for the contribution. I am not sure whether smilodon would be able to mount block devices from inside docker container. Have you had a chance to test that?

**Comment by rowleyaj** [comment]
Hey @vaijab, thats a very good point.

I hadn't got that far yet in my testing. I only tested that the container built and the app ran. I was going to test it on an instance today. Since I overlooked that aspect though my intentions with my PR here might not work. My reason for wanting to put it into a container was to easily run this on Container Linux.

When you were using this did you deploy this to the host OS using standard system packages?

**Comment by lewismarshall** [comment]
Hi @rowleyaj, the main problem is that smiladon needs to be able to mount devices. Here's the unit file we use in keto (for use on CoreOS):
```
      [Unit]
      Description=Smilodon - manage ebs+eni attachment
      [Service]
      Environment="URL=https://github.com/UKHomeOffice/smilodon/releases/download/v0.0.4/smilodon-0.0.4-linux-amd64"
      Environment="OUTPUT_FILE=/opt/bin/smilodon"
      Environment="MD5SUM=071d32e53fdb53fa17c7bbe03744fdf6"
      ExecStartPre=/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/bash -c 'until [[ -x ${OUTPUT_FILE} ]] && [[ $(md5sum ${OUTPUT_FILE} | cut -f1 -d" ") == ${MD5SUM} ]]; do wget -q -O ${OUTPUT_FILE} ${URL} && chmod +x ${OUTPUT_FILE}; done'
      ExecStart=/opt/bin/smilodon \
        --filters='tag:managed-by-keto:true,tag:cluster-name={{ .ClusterName }},tag-key=NodeID' \
        --create-file-system \
        --mount-fs \
        --mount-point=/data
      Restart=always
      RestartSec=10
      TimeoutStartSec=300
```

If this is possible to mount devices within docker with the smiladon then it's worth it but otherwise this could be a blocker to it's use.

**Comment by rowleyaj** [comment]
Hey @vaijab @lewismarshall,

I tested the container on an instance today, you're both right that it can't create mounts on the host. I figured it must be possible to do this somehow though since "everything is a file", so did some further research.

If a privileged container is used, and certain directories mounted it is possible to mount on the host:
`docker run -ti --privileged -v /:/host -v /dev:/dev --entrypoint /bin/sh rowleyaj/smilodon`
`nsenter --mount=/host/proc/1/ns/mnt -- /usr/bin/mount -t ext4 /dev/xvde /data`

I'm not sure of the security implications of doing this, so it does raise the question of just because it is possible, does it necessarily mean it should be done? Would appreciate your thoughts on this point in particular.

As a side note, the current container I built is missing the programs that smilodon uses to check if the filesystem has been created, and create it if not but these could easily be added. I also modified the container to use entrypoint in the dockerfile so it could be treated as the smilodon program directly, which is why --entrypoint is used above.

If this was a route forward perhaps we could add an environment variable to the dockerfile so that smilodon is aware it is running from a container, and then use the modified commands. 

Reference: https://developers.redhat.com/blog/2014/11/06/introducing-a-super-privileged-container-concept/

**Pull request closed without merging**
